export const PRICING = {
  FREE: 0,
  STANDARD: 5000,
  PREMIUM: 20000,
  CUSTOM_STANDARD_PER_CHAPTER: 1500,
  CUSTOM_PREMIUM_PER_CHAPTER: 5000,
};

export const PRICING_FORMATTED = {
  FREE: '₦0',
  STANDARD: `₦${PRICING.STANDARD.toLocaleString()}`,
  PREMIUM: `₦${PRICING.PREMIUM.toLocaleString()}`,
  CUSTOM_STANDARD_PER_CHAPTER: `₦${PRICING.CUSTOM_STANDARD_PER_CHAPTER.toLocaleString()}/ch`,
  CUSTOM_PREMIUM_PER_CHAPTER: `₦${PRICING.CUSTOM_PREMIUM_PER_CHAPTER.toLocaleString()}/ch`,
};

export const INTERNATIONAL_PRICING = {
  STANDARD: 5,
  PREMIUM: 20,
  CUSTOM_STANDARD_PER_CHAPTER: 1.5,
  CUSTOM_PREMIUM_PER_CHAPTER: 5.0,
};

export const INTERNATIONAL_PRICING_FORMATTED = {
  STANDARD: '$5',
  PREMIUM: '$20',
  CUSTOM_STANDARD_PER_CHAPTER: '$1.50/ch',
  CUSTOM_PREMIUM_PER_CHAPTER: '$5/ch',
};
