// src/lib/slideTemplates.js

export const SLIDE_TEMPLATES = [
  {
    id: 'academic',
    name: 'Academic Professional',
    description: 'Clean, professional template for academic project presentations',
    primaryColor: '#1e3a5f',
    secondaryColor: '#2c5282',
    accentColor: '#3182ce',
    textColor: '#ffffff',
    bodyBg: '#ffffff',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'modern',
    name: 'Modern Minimal',
    description: 'Modern, minimal design with bold typography',
    primaryColor: '#0f172a',
    secondaryColor: '#1e293b',
    accentColor: '#3b82f6',
    textColor: '#ffffff',
    bodyBg: '#ffffff',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'sunset',
    name: 'Sunset Glow',
    description: 'Warm sunset gradient with coral and amber tones',
    primaryColor: '#7c2d12',
    secondaryColor: '#c2410c',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    bodyBg: '#ffffff',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'royal',
    name: 'Royal Purple',
    description: 'Elegant purple theme with gold accents',
    primaryColor: '#581c87',
    secondaryColor: '#7c3aed',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    bodyBg: '#ffffff',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  {
    id: 'forest',
    name: 'Forest Nature',
    description: 'Calming green palette inspired by nature',
    primaryColor: '#14532d',
    secondaryColor: '#166534',
    accentColor: '#84cc16',
    textColor: '#ffffff',
    bodyBg: '#ffffff',
    fontFamily: 'Inter, system-ui, sans-serif',
  }
];
